// <auto-generated />
namespace Devrekani_Sehitler_Kutuphanesi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class two : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(two));
        
        string IMigrationMetadata.Id
        {
            get { return "202412182119279_two"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
