//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcKutuphane.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Penalties
    {
        public int Id { get; set; }
        public Nullable<int> Member_Id { get; set; }
        public Nullable<int> Transaction_Id { get; set; }
        public Nullable<System.DateTime> StartPenalty { get; set; }
        public Nullable<System.DateTime> FinishPenalty { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual Members Members { get; set; }
        public virtual Transactions Transactions { get; set; }
    }
}
